CREATE TABLE Wards(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR,
    MAX_COUNT INTEGER
);

CREATE TABLE Diagnosis(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR
);

CREATE TABLE People(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    PATHER_NAME VARCHAR,
    DIAGNOSIS_ID INTEGER,
    WARD_ID INTEGER,
    FOREIGN KEY (DIAGNOSIS_ID) REFERENCES DIAGNOSIS(ID),
    FOREIGN KEY (WARD_ID) REFERENCES WARDS(ID)
);
